kelasterbuka/blog/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('recent/', views.recent, name="recent"),
    path('story/', views.story, name="story"),
    path('news/', views.news, name="news"),
    path('non-category/', views.noncategory, name="noncategory"),
    path('', views.index, name="index"),
    re_path(r'^(?P<input>[0-9]{2})/$', views.angka, name="angka"),
    re_path(r'^(?P<tahun>[0-9]{4})/(?P<bulan>[0-9]{2})/(?P<hari>[0-9]{2})/$', views.tanggal, name="tanggal"),
    re_path(r'^(?P<page>[\w_]+)/$', views.link, name="link"),
    re_path(r'^(?P<categoryInput>[\w-]+)/$', views.categoryPost, name="categoryPost"),
    re_path(r'^post/(?P<slugInput>[\w-]+)/$', views.singlePost, name="singlePost"),
]

kelasterbuka/blog2/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
]

kelasterbuka/kelasterbuka/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', include(('about.urls', 'about'), namespace="about")),
    path('contact/', include(('contact.urls', 'contact'), namespace="contact")),
    path('blog/', include(('blog.urls', 'blog'), namespace="blog")),
    path('blog2/', include(('blog2.urls', 'blog2'), namespace="blog2")),
    path('sosmed/', include(('sosmed.urls', 'sosmed'), namespace="sosmed")),
    path('admin/', admin.site.urls),
]

kelasterbuka/blog2/models.py
from django.db import models

from .validators import validate_author

# Create your models here.
class Post(models.Model):
    judul       = models.CharField(max_length=100)
    body        = models.TextField()
    author      = models.CharField(
        max_length=100,
        validators= [validate_author]   # memasukkan validasi, jenis: list, tidak perlu makemigrations
    )

    LIST_CATEGORY = (
        ('Jurnal', 'jurnal'),
        ('Lagu', 'lagu'),
        ('Curhat', 'curhat'),
    )
    category    = models.CharField(
        max_length=100,
        choices=LIST_CATEGORY,
        default='Curhat',
    )

    def __str__(self):
        return "{}. {}".format(self.id, self.judul)

kelasterbuka/blog2/forms.py
from django import forms

from .models import Post

# menggunakan cara lama, mencocokkan langsung dengan models.py
'''
class PostForm(forms.Form):
    judul       = forms.CharField(max_length=100)
    body        = forms.CharField(widget=forms.Textarea)
    category    = forms.CharField(max_length=100)
'''

# menggunakan Model Form
class PostForm(forms.ModelForm):
    # mengakses dari inheritance class Model (models.py)
    class Meta:
        model = Post
        # tampilkan fields apa saja yang ingin diambil dari Model untuk form
        fields  = ['author', 'judul', 'body', 'category']
        # menambahkan atribut field (option aja)
        labels = {
            'author': 'Penulis'
        }
        widgets = {
            'judul': forms.TextInput(
                attrs   = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan judul',
                }
            ),
            'author': forms.TextInput(
                attrs   = {
                    'class': 'form-control',
                    'placeholder': 'Masukkan nama penulis',
                }
            ),
            'body': forms.Textarea(
                attrs   = {
                    'class': 'form-control',
                }
            ),
            'category': forms.Select(
                attrs   = {
                    'class': 'form-control',
                }
            ),
        }

kelasterbuka/blog2/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .forms import PostForm
from .models import Post

def index(request):
    posts = Post.objects.all()
    context = {
        'page_title': 'Post List',
        'posts': posts,
    }
    return render(request, 'blog2/index.html', context)

def create(request):
    # apabila tidak ada POST, maka dilakukan proses membuat object baru tanpa nilai isian (None)
    # apabila ada POST, maka dilakukan proses membuat object baru dengan nilai dari request POST tsb
    post_form = PostForm(request.POST or None)
    if request.method == 'POST':
        if post_form.is_valid():
            post_form.save()    # tidak perlu mengganti create seperti di bawah ketika ada perubahan
            '''
            Post.objects.create(
                judul       = request.POST.get('judul'),
                body        = request.POST.get('body'),
                category    = request.POST.get('category'),
            )
            '''
            return redirect('blog2:index')
    context = {
        'post_title': 'Create Post',
        'post_form': post_form,
    }
    return render(request, 'blog2/create.html', context)

kelasterbuka/blog2/templates/blog2/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page_title}}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <ul>
            <li><a href="{% url "blog2:index" %}">Home</a></li>
            <li><a href="{% url "blog2:create" %}">Create</a></li>
        </ul>
        <h1 style="color: blue;">{{page_title}}</h1>
        <form method="POST">
            {% csrf_token %}
            {% for form in post_form %}
            <div class="form-group">
                {{form.label}}
                {{form}}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-success">Kirim</button>
        </form>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

kelasterbuka/blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page_title}}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <ul>
            <li><a href="{% url "blog2:index" %}">Home</a></li>
            <li><a href="{% url "blog2:create" %}">Create</a></li>
        </ul>
        <h1 style="color: red;">{{page_title}}</h1>
        
        {% for post in posts %}
            <h2>{{post.author}}</h2>
            <h1>{{post.judul}}</h1>
            <p>{{post.body}}</p>
            <p><i>{{post.category}}</i></p>
        {% endfor %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>