kelasterbuka-latihan1/blog/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    re_path(r'^category/(?P<categoryInput>[\w-]+)/$', views.categoryPost, name="category"),
    re_path(r'^post/(?P<slugInput>[\w-]+)/$', views.detailPost, name="detail"),
]

kelasterbuka-latihan1/mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', include(('blog.urls', 'blog'), namespace="blog")),
    path('admin/', admin.site.urls),
]

kelasterbuka-latihan1/blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class Post(models.Model):
    judul = models.CharField(max_length=255)
    body = models.TextField()
    category = models.CharField(max_length=255)
    publish = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, editable=False)

    def save(self):
        self.slug = slugify(self.judul)
        super(Post, self).save()

    def __str__(self):
        return "{}. {}".format(self.id, self.judul)

kelasterbuka-latihan1/blog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Post

def index(request):
    posts = Post.objects.all()
    categories = Post.objects.values('category').distinct()
    context = {
        'Judul': 'Home Blog',
        'Content': 'Ini adalah Halaman Home Blog',
        'Posts': posts,
        'Categories': categories,
    }
    return render(request, 'blog/index.html', context)

def categoryPost(request, categoryInput):
    posts = Post.objects.filter(category=categoryInput)
    categories = Post.objects.values('category').distinct()
    context = {
        'Judul': 'Home Blog',
        'Content': 'Tampilkan Berdasarkan Kategori',
        'Posts': posts,
        'Categories': categories,
    }
    return render(request, 'blog/category.html', context)

def detailPost(request, slugInput):
    posts = Post.objects.get(slug=slugInput)
    categories = Post.objects.values('category').distinct()
    context = {
        'Judul': 'Home Blog',
        'Content': 'Ini adalah Halaman Home Blog',
        'Posts': posts,
        'Categories': categories,
    }
    return render(request, 'blog/detail.html', context)

kelasterbuka-latihan1/mywebsite/views.py
from django.shortcuts import render

def index(request):
    context = {
        'Judul': 'Home Page',
        'Content': 'Ini adalah Home Page dari Website ini',
    }
    return render(request, 'index.html', context)

kelasterbuka-latihan1/blog/templates/blog/category.html
{% extends "base.html" %}

{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block Contents %}
    {{Content}}
    <ul class="nav">
            <li class="nav-item">
                <a href="/blog" class="nav-link">All-Post</a>
            </li>
        {% for dataCategory in Categories %}
            <li class="nav-item">
                <a href="/blog/category/{{dataCategory.category}}" class="nav-link">
                    {{dataCategory.category}}
                </a>
            </li>
        {% endfor %}
    </ul>
    {% for post in Posts %}
        <a href="/blog/post/{{post.slug}}">
            <h1>{{post.judul}}</h1>
        </a>
        <p>{{post.publish}}</p>
        <p>{{post.body|truncatechars:200}}</p>
    {% endfor %}
{% endblock Contents %}

kelasterbuka-latihan1/blog/templates/blog/detail.html
{% extends "base.html" %}

{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block Contents %}
    {{Content}}
    <ul class="nav">
            <li class="nav-item">
                <a href="/blog" class="nav-link">All-Post</a>
            </li>
        {% for dataCategory in Categories %}
            <li class="nav-item">
                <a href="/blog/category/{{dataCategory.category}}" class="nav-link">
                    {{dataCategory.category}}
                </a>
            </li>
        {% endfor %}
    </ul>
    <h1>{{Posts.judul}}</h1>
    <p>{{Posts.publish}}</p>
    <p>{{Posts.body}}</p>
{% endblock Contents %}

kelasterbuka-latihan1/blog/templates/blog/index.html
{% extends "base.html" %}

{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block Contents %}
    {{Content}}
    <ul class="nav">
            <li class="nav-item">
                <a href="{% url "blog:index" %}" class="nav-link">All-Post</a>
            </li>
        {% for dataCategory in Categories %}
            <li class="nav-item">
                <a href="{% url "blog:category" categoryInput=dataCategory.category %}" class="nav-link">
                    {{dataCategory.category}}
                </a>
            </li>
        {% endfor %}
    </ul>
    {% for post in Posts %}
        <a href="{% url "blog:detail" slugInput=post.slug %}">
            <h1>{{post.judul}}</h1>
        </a>
        <p>{{post.publish}}</p>
        <p>{{post.body|truncatechars:200}}</p>
    {% endfor %}
{% endblock Contents %}

kelasterbuka-latihan1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block Title %}
        {% endblock Title %}
    </title>
    {% include "snippets/styles.html" %}
</head>
<body>
    
    {% include "snippets/navbar.html" %}
    <div class="container" style="margin-top: 100px;">
        <h1>
            {% block pageTitle %}
            {% endblock pageTitle %}
        </h1>
    </div>
    <div class="container bg-light shadow mt-5">
        {% block Contents %}
        {% endblock Contents %}
    </div>

    {% include "snippets/scripts.html" %}
</body>
</html>

kelasterbuka-latihan1/templates/index.html
{% extends "base.html" %}

{% block Title %}
    {{Judul}}
{% endblock Title %}

{% block pageTitle %}
    {{Judul}}
{% endblock pageTitle %}

{% block Contents %}
    {{Content}}
{% endblock Contents %}

kelasterbuka-latihan1/templates/snippets/navbar.html
<nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">
            <h1>Kelas Terbuka</h1>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url "index" %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url "blog:index" %}" class="nav-link">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="{% url "admin:index" %}" class="nav-link">Admin</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

kelasterbuka-latihan1/templates/snippets/scripts.html
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

kelasterbuka-latihan1/templates/snippets/styles.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">