kelasterbuka/blog/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('recent/', views.recent, name="recent"),
    path('story/', views.story, name="story"),
    path('news/', views.news, name="news"),
    path('non-category/', views.noncategory, name="noncategory"),
    path('', views.index, name="index"),
    re_path(r'^(?P<input>[0-9]{2})/$', views.angka, name="angka"),
    re_path(r'^(?P<tahun>[0-9]{4})/(?P<bulan>[0-9]{2})/(?P<hari>[0-9]{2})/$', views.tanggal, name="tanggal"),
    re_path(r'^(?P<page>[\w_]+)/$', views.link, name="link"),
    re_path(r'^(?P<categoryInput>[\w-]+)/$', views.categoryPost, name="categoryPost"),
    re_path(r'^post/(?P<slugInput>[\w-]+)/$', views.singlePost, name="singlePost"),
]

kelasterbuka/kelasterbuka/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', include(('about.urls', 'about'), namespace="about")),
    path('contact/', include(('contact.urls', 'contact'), namespace="contact")),
    path('blog/', include(('blog.urls', 'blog'), namespace="blog")),
    path('blog2/', include(('blog2.urls', 'blog2'), namespace="blog2")),
    path('sosmed/', include(('sosmed.urls', 'sosmed'), namespace="sosmed")),
    path('admin/', admin.site.urls),
]

kelasterbuka/sosmed/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    re_path(r'^delete/(?P<delete_id>[0-9]+)/$', views.delete, name="delete"),
    re_path(r'^update/(?P<update_id>[0-9]+)/$', views.update, name="update"),
]

kelasterbuka/sosmed/models.py
from django.db import models

# Create your models here.
class Instagram(models.Model):
    nama_depan      = models.CharField(max_length=100)
    nama_belakang   = models.CharField(max_length=100)
    username        = models.CharField(max_length=100)

    def __str__(self):
        return "{}. {}".format(self.id, self.username)

kelasterbuka/sosmed/forms.py
from django import forms

from .models import Instagram

class InstagramForm(forms.ModelForm):
    class Meta:
        model   = Instagram
        fields  = ['nama_depan', 'nama_belakang', 'username']

kelasterbuka/sosmed/views.py
from django.shortcuts import render, redirect

from .models import Instagram
from .forms import InstagramForm

# Create your views here.
def index(request):
    akun    = Instagram.objects.all()
    context = {
        'page_title': 'Media Sosial',
        'akun_all': akun,
    }
    return render(request, 'sosmed/index.html', context)

def create(request):
    akun_form   = InstagramForm(request.POST or None)
    if request.method == 'POST':
        if akun_form.is_valid():
            akun_form.save()
        return redirect('sosmed:index')
    context = {
        'page_title': 'Tambah Akun',
        'akun_form': akun_form,
    }
    return render(request, 'sosmed/create.html', context)

def delete(request, delete_id):
    Instagram.objects.filter(id=delete_id).delete()
    return redirect('sosmed:index')

def update(request, update_id):
    akun_update = Instagram.objects.get(id=update_id)
    data = {
        'nama_depan': akun_update.nama_depan,
        'nama_belakang': akun_update.nama_belakang,
        'username': akun_update.username,
    }
    akun_form = InstagramForm(request.POST or None, initial=data, instance=akun_update)
    if request.method == 'POST':
        if akun_form.is_valid():
            akun_form.save()
        return redirect('sosmed:index')
    context = {
        'page_title': 'Ubah Akun',
        'akun_form': akun_form,
    }
    return render(request, 'sosmed/create.html', context)

kelasterbuka/sosmed/templates/sosmed/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{page_title}}</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block contents %}
        {% endblock contents %}
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

kelasterbuka/sosmed/templates/sosmed/create.html
{% extends "sosmed/base.html" %}

{% block contents %}
    <h1>{{page_title}}</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{akun_form.as_table}}
        </table>
        <button type="submit">Kirim</button>
    </form>
{% endblock contents %}

kelasterbuka/sosmed/templates/sosmed/index.html
{% extends "sosmed/base.html" %}

{% block contents %}
    <h1>{{page_title}}</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Username</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for akun in akun_all %}
            <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td>{{akun.nama_depan}}</td>
                <td>{{akun.nama_belakang}}</td>
                <td>{{akun.username}}</td>
                <td>
                    <a href="{% url "sosmed:delete" akun.id %}" class="btn btn-danger">Hapus</a>
                    <a href="{% url "sosmed:update" akun.id %}" class="btn btn-warning">Ubah</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url "sosmed:create" %}" class="btn btn-primary">Tambah</a>
{% endblock contents %}